# Generated by Django 3.0 on 2022-01-09 13:19

import api_v0.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=api_v0.models.upload_path),
        ),
    ]
