# Generated by Django 3.0 on 2022-01-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0002_comment'),
        ('api_v0', '0003_auto_20220109_1510'),
    ]

    operations = [
    ]
